version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        build: ./
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    db:
        image: mysql:5.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lehangarlocal
            MYSQL_USER: user
            MYSQL_PASSWORD: user

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8000:8000
        environment:
            - PMA_ARBITRARY=1
    composer:
        image: composer
        volumes: 
            - .:/var/www
        working_dir: /var/www



