name: Lint

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
          
      - name: npm ci
        run: npm ci
        
      - name: Run Stylelint css
        run: npm run csslint

      - name: Run Stylelint
        run: npm run scsslint
        
      - name: Run ESLint
        run: npm run eslint
        
      - name: Run HTML-Validate
        run: npm run html-validate

      - name: Get composer cache directory
        id: composer_config
        uses: baschny/php-composer-action@v1
        with:
          command: get_config

      - name: Cache composer downloads
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer_config.outputs.composer_cache_dir }}
          key: composer-v${{ steps.composer_config.outputs.composer_major_version }}

      - name: Run composer install
        uses: baschny/php-composer-action@v1
        
      - name: Run PHPlint
        run: npm run phplint
