name: Lint

on:
  workflow_dispatch:
  pull_request:

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
        
  npm:
    name: Install Node Packages
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
        
      - name: npm ci
        run: npm ci
        
      - uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules
        
  composer:
    name: Install Composer packages
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
        
      - name: Get composer cache directory
        id: composer_config
        uses: baschny/php-composer-action@v1
        with:
          command: get_config

      - name: Cache composer downloads
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer_config.outputs.composer_cache_dir }}
          key: composer-v${{ steps.composer_config.outputs.composer_major_version }}

      - name: Run composer install
        uses: baschny/php-composer-action@v1
        
      - uses: actions/upload-artifact@v2
        with:
          name: vendor
          path: vendor
        
  css:
    name: Lint css
    runs-on: ubuntu-latest
    needs: [npm]
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
        
      - uses: actions/download-artifact@v2
        with:
          name: node_modules
    
      - name: Run Stylelint css
        run: npm run csslint
        
  scss:
    name: Lint scss
    runs-on: ubuntu-latest
    needs: [npm]
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
        
      - uses: actions/download-artifact@v2
        with:
          name: node_modules
          
      - name: Run Stylelint scss
        run: npm run scsslint
        
  js:
    name: Lint js
    runs-on: ubuntu-latest
    needs: [npm]
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
        
      - uses: actions/download-artifact@v2
        with:
          name: node_modules
    
      - name: Run ESLint
        run: npm run eslint
        
  html:
    name: Lint html
    runs-on: ubuntu-latest
    needs: [npm]
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
        
      - uses: actions/download-artifact@v2
        with:
          name: node_modules
    
      - name: Run HTML-Validate
        run: npm run html-validate
  
  twig:
    name: Lint twig
    runs-on: ubuntu-latest
    needs: [npm]
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
        
      - uses: actions/download-artifact@v2
        with:
          name: node_modules
    
      - name: Run HTML-Validate for .twig files
        run: npm run twig-validate
        
  php:
    name: Lint PHP
    runs-on: ubuntu-latest
    needs: [composer]
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
        
      - uses: actions/download-artifact@v2
        with:
          name: vendor
    
      - name: Run PHPlint
        run: npm run phplint

  alldone:
    name: All linters done
    runs-on: ubuntu-latest
    needs: [css, scss, js, html, twig, php]
    steps:
      - name: All done
        run: echo "All done !"
